### ISSUE TITLE
AVX2 binaries won't be able to re-distribute

### ISSUE THREAD

**Issue by FrancescAlted** [Blosc/c-blosc#101]
@juliantaylor just warned about the possibility that if someone creates a binary with AVX2, then this won't work in non-SSE2 machines.  This is in fact a big problem because Blosc tends to be embedded in larger binary packages.  The only solution would be to disable AVX2 usage on non-AVX2 machines.  @littlezhou do you think this can be done easily?

**Comment by juliantaylor** [comment]
the best way to get the best performance from the available hardware is to dispatch to different functions depending on the hardware at runtime, e.g. via GCC's `__builtin_cpu_supports("avx")` though doing that compiler independent is not as nice. I can probably give this a try at least for gcc only.

**Comment by juliantaylor** [comment]
see #102 for how one could do it

**Comment by FrancescAlted** [comment]
PR #108 also addresses this in a more general way.  Closing.
