### ISSUE TITLE
AVX2 implementation segfaults

### ISSUE THREAD

**Issue by FrancescAlted** [Blosc/c-blosc#106]
Here it is a way to make it crash (on a AVX2 machine because on a SSE2 one this works well):

```
 ~/c-blosc/build $ bench/bench blosclz single 1 262140 4 4
Blosc version: 1.6.1.dev ($Date:: 2015-04-20 #$)
List of supported compressors in this build: blosclz,lz4,lz4hc,snappy,zlib
Supported compression libraries:
  BloscLZ: 1.0.3
  LZ4: 1.6.0
  Snappy: 1.1.1
  Zlib: 1.2.8
Using compressor: blosclz
Running suite: single
--> 1, 262140, 4, 4, blosclz
********************** Run info ******************************
Blosc version: 1.6.1.dev ($Date:: 2015-04-20 #$)
Using synthetic data with 4 significant bits (out of 32)
Dataset size: 262140 bytes      Type size: 4 bytes
Working set: 256.0 MB           Number of threads: 1
********************** Running benchmarks *********************
memcpy(write):             31.8 us, 7850.6 MB/s
memcpy(read):              21.1 us, 11845.5 MB/s
Compression level: 0
comp(write):       22.3 us, 11206.0 MB/s          Final bytes: 262156  Ratio: 1.00
decomp(read):      21.1 us, 11855.2 MB/s          OK
Compression level: 1
comp(write):       41.5 us, 6027.8 MB/s   Final bytes: 2216  Ratio: 118.29
Segmentation fault
``` 

This is using current master.  @littlezhou can you have a look at this please?

**Comment by littlezhou** [comment]
I cloned the latest source code, It works well on my machine, do you have fixed it ?

[root@bdlab build]# ./bench/bench  blosclz single 1 262140 4 4
Blosc version: 1.6.1.dev ($Date:: 2015-04-20 #$)
List of supported compressors in this build: blosclz,lz4,lz4hc,snappy,zlib
Supported compression libraries:
  BloscLZ: 1.0.3
  LZ4: 1.6.0
  Snappy: 1.1.1
  Zlib: 1.2.3
Using compressor: blosclz
Running suite: single
--> 1, 262140, 4, 4, blosclz
********************** Run info ******************************
Blosc version: 1.6.1.dev ($Date:: 2015-04-20 #$)
Using synthetic data with 4 significant bits (out of 32)
Dataset size: 262140 bytes      Type size: 4 bytes
Working set: 256.0 MB           Number of threads: 1
********************** Running benchmarks *********************
memcpy(write):             43.9 us, 5700.1 MB/s
memcpy(read):              23.3 us, 10748.0 MB/s
Compression level: 0
comp(write):       30.1 us, 8297.5 MB/s   Final bytes: 262156  Ratio: 1.00
decomp(read):      23.3 us, 10736.5 MB/s          OK
Compression level: 1
comp(write):       56.3 us, 4443.9 MB/s   Final bytes: 2216  Ratio: 118.29
decomp(read):      48.5 us, 5154.6 MB/s   OK
Compression level: 2
comp(write):       56.9 us, 4394.3 MB/s   Final bytes: 2216  Ratio: 118.29
decomp(read):      48.5 us, 5157.2 MB/s   OK
Compression level: 3
comp(write):       56.9 us, 4393.9 MB/s   Final bytes: 2216  Ratio: 118.29
decomp(read):      48.5 us, 5153.7 MB/s   OK
Compression level: 4
comp(write):       58.4 us, 4278.3 MB/s   Final bytes: 1616  Ratio: 162.22
decomp(read):      59.2 us, 4220.0 MB/s   OK
Compression level: 5
comp(write):       58.4 us, 4277.9 MB/s   Final bytes: 1616  Ratio: 162.22
decomp(read):      59.3 us, 4215.4 MB/s   OK
Compression level: 6
comp(write):       67.0 us, 3730.9 MB/s   Final bytes: 1311  Ratio: 199.95
decomp(read):      74.1 us, 3373.5 MB/s   OK
Compression level: 7
comp(write):       77.5 us, 3223.7 MB/s   Final bytes: 1160  Ratio: 225.98
decomp(read):     105.7 us, 2364.0 MB/s   OK
Compression level: 8
comp(write):       77.5 us, 3224.0 MB/s   Final bytes: 1160  Ratio: 225.98
decomp(read):     105.6 us, 2366.3 MB/s   OK
Compression level: 9
comp(write):      130.3 us, 1918.2 MB/s   Final bytes: 1117  Ratio: 234.68
decomp(read):     192.0 us, 1302.1 MB/s   OK

Round-trip compr/decompr on 7.5 GB
Elapsed time:       4.6 s, 3650.2 MB/s
[root@bdlab build]#

**Comment by FrancescAlted** [comment]
Strange, because I can reproduce the segfault in my machine, irregardless of the compressor used.  Maybe is an error related with the environment?  I am using Gentoo with gcc 4.9.2, you?

**Comment by FrancescAlted** [comment]
Just tried with gcc 4.8.4 in the same machine and I continue to be able to reproduce the issue :-/

**Comment by littlezhou** [comment]
My machine is CentOS 6.5. I test the code with ICC and GCC4.9.2, both of them works well.

**Comment by jack-pappas** [comment]
I'm able to reproduce this on Windows when compiling with VS2013 and VC++.

I don't know that the issue is AVX2-related though. While working on #108, I had an intermediate step after 48ee347 where everything was more or less in place except the CPU feature detection. I compiled and ran (and got the generic/unoptimized implementation as expected) and ``bench`` still crashed. On my machine, it crashes after printing the "OK" for the compression level 9 results (but before the round-trip stats are displayed). I tried again after finishing the code for #108 and the same thing happens, even though this time I was running the AVX2-accelerated code.

**Comment by juliantaylor** [comment]
looks like a typo in https://github.com/Blosc/c-blosc/blob/master/blosc/shuffle-avx2.c#L257 introduced only recently

**Comment by FrancescAlted** [comment]
Typo confirmed.  After fixing this:

```
$ bench/bench blosclz single 1 262140 4 4
Blosc version: 1.6.1.dev ($Date:: 2015-04-20 #$)
List of supported compressors in this build: blosclz,lz4,lz4hc,snappy,zlib
Supported compression libraries:
  BloscLZ: 1.0.3
  LZ4: 1.6.0
  Snappy: 1.1.1
  Zlib: 1.2.8
Using compressor: blosclz
Running suite: single
--> 1, 262140, 4, 4, blosclz
********************** Run info ******************************
Blosc version: 1.6.1.dev ($Date:: 2015-04-20 #$)
Using synthetic data with 4 significant bits (out of 32)
Dataset size: 262140 bytes      Type size: 4 bytes
Working set: 256.0 MB           Number of threads: 1
********************** Running benchmarks *********************
memcpy(write):             32.5 us, 7690.5 MB/s
memcpy(read):              21.2 us, 11786.0 MB/s
Compression level: 0
comp(write):       22.8 us, 10988.5 MB/s          Final bytes: 262156  Ratio: 1.00
decomp(read):      21.2 us, 11815.3 MB/s          OK
Compression level: 1
comp(write):       41.5 us, 6025.4 MB/s   Final bytes: 2216  Ratio: 118.29
decomp(read):      33.0 us, 7568.6 MB/s   OK
Compression level: 2
comp(write):       42.1 us, 5943.4 MB/s   Final bytes: 2216  Ratio: 118.29
decomp(read):      33.0 us, 7582.7 MB/s   OK
Compression level: 3
comp(write):       42.3 us, 5909.5 MB/s   Final bytes: 2216  Ratio: 118.29
decomp(read):      33.0 us, 7568.5 MB/s   OK
Compression level: 4
comp(write):       45.9 us, 5451.3 MB/s   Final bytes: 1616  Ratio: 162.22
decomp(read):      44.3 us, 5648.2 MB/s   OK
Compression level: 5
comp(write):       46.0 us, 5432.9 MB/s   Final bytes: 1616  Ratio: 162.22
decomp(read):      44.1 us, 5668.9 MB/s   OK
Compression level: 6
comp(write):       58.9 us, 4245.9 MB/s   Final bytes: 1311  Ratio: 199.95
decomp(read):      63.8 us, 3921.2 MB/s   OK
Compression level: 7
comp(write):       73.9 us, 3384.0 MB/s   Final bytes: 1160  Ratio: 225.98
decomp(read):     106.5 us, 2348.3 MB/s   OK
Compression level: 8
comp(write):       74.0 us, 3379.0 MB/s   Final bytes: 1160  Ratio: 225.98
decomp(read):     106.6 us, 2345.3 MB/s   OK
Compression level: 9
comp(write):      135.1 us, 1850.4 MB/s   Final bytes: 1117  Ratio: 234.68
decomp(read):     206.6 us, 1209.9 MB/s   OK

Round-trip compr/decompr on 7.5 GB
Elapsed time:       4.1 s, 4117.8 MB/s
```

Thanks a lot Julian!
