### ISSUE TITLE
Use emulation to support AVX2 tests on CI builds

### ISSUE THREAD

**Issue by jack-pappas** [Blosc/c-blosc#138]
Neither the travis-ci or AppVeyor builds currently run on hardware with AVX2 support, meaning any changes made to the AVX2 shuffle need to be tested manually.

It should be possible to run the tests under an emulator like [Intel SDE](https://software.intel.com/en-us/articles/intel-software-development-emulator/) or [QEMU](http://wiki.qemu.org/Main_Page) so they can run automatically as part of the CI builds even when the underlying hardware doesn't support certain CPU features. QEMU even goes one step further and can emulate other CPU architectures too, e.g., to allow running tests for an ARM NEON shuffle on the x86 hardware used by the CI platforms.

**Comment by jeffhammond** [comment]
FYI:

- https://github.com/marehr/intel-sde-downloader
- https://github.com/mmcloughlin/meow/blob/871e50784daff1c9ec5ef66fe3d8fda6bbcd42cf/.travis.yml

**Comment by nmoinvaz** [comment]
@FrancescAlted this can be closed, GitHub Actions machines support AVX2.

**Comment by FrancescAlted** [comment]
Right.  Closing.
