### ISSUE TITLE
Windows binaries

### ISSUE THREAD

**Issue by buybackoff** [Blosc/c-blosc#148]
I have compiled the version 1.7 with CMake and VS2013/15 and noticed that in the package, the `bin` folder contains `msvcrXX` and `msvcpXX `. Does Blosc have dependencies on those Microsoft libraries when compiled with VS, or this is a CMake/VS artifact? (I do not have access to Windows without Visual Studio, cannot quickly test if the runtime libraries are needed because they are installed system-wide.)

Additionally, it would be very kind of you to release MinGW x86/x64 binaries. Especially in the light of  the latest blog post: http://www.blosc.org/blog/hairy-msvc-situation.rst.html. At my current PC at work I do not have MinGW toolchain and prospects to set it up from scratch again scare me a lot. One of the cool features of Blosc is run-time detection of SSE/AVX, so there is no reason to recompile binaries for each hardware config.

**Comment by FrancescAlted** [comment]
Hmm, C-Blosc does not distributed any bin/ directory, so this should be a result of your compilation.

And sorry, but we cannot promise creating binaries for any platform, and this should be the responsibility of the users or other packagers.  But if you are willing to [sponsor us](http://blosc.org/blog/seeking-sponsoship.html) this could be done on a regular basis.

**Comment by buybackoff** [comment]
CMake creates a PACKAGE project, and its output contains `bin`, `include`, and `lib` folders.

**Comment by buybackoff** [comment]
In MinGW makefiles, `-msse2` should be `-mavx2`, e.g. here https://github.com/Blosc/c-blosc/blob/master/bench/Makefile.mingw#L3.

BTW, I have built MinGW x64 version with GCC 4.9.2 and compared it to VS2015RC, and VS2015 performance wins accross the board on the same data on my benchmarks. With a huge margin.

And I could also confirm that #84 is ok with 1.7 and MinGW on x64.

**Comment by FrancescAlted** [comment]
Good point.  However, I have just tested the bench/ Makefile and it fails.  This is expected as I do not maintain them for quite a long time, so I think the best is to remove them and promote cmake as the only supported way to compile C-Blosc (much more flexible and with discovery capabilities for SSE2 and AVX2).

And I am certainly interested in having a look at your VS2015 benchmarks (specially compared with MinGW-w64 4.9.x), so please share them when you can :)

**Comment by buybackoff** [comment]
Just have tested this on a fresh Windows 8.1 install, both VS CMake and MinGW builds fail without MSVCR120.dll. It is strange that MinGW version requires it, given that the dll is several times larger in size than the VS's version.

**Comment by buybackoff** [comment]
Closing this because redistributing `msvcrt` became inevitable and CMake build with MSVC is very easy on any machine compared to Makefile with MinGW. Any performance differences between MSVC and MinGW are not relevant, both are fast.

Just FYI, I use Blosc in my [Spreads](https://github.com/Spreads/Spreads/blob/master/src/Spreads.Extensions/Serializer.cs) project and it is very good and stable! In .NET, there is a decimal data type that takes 128 bits. The cool and funny thing is that if I convert `double` to `decimal` arrays, which are 2x larger, and then compress them, the resulting size is significantly lower than the size of compressed `double` arrays (and without precision loss). This is due to byte representation of `decimal`, and shuffling shines here. Thanks again for this nice library!
