### ISSUE TITLE
Using blosc for zram

### ISSUE THREAD

**Issue by rrva** [Blosc/c-blosc#149]
This is more of a question/idea:

Has anyone looked into using blosc for zram compression? 

https://www.kernel.org/doc/Documentation/blockdev/zram.txt

**Comment by FrancescAlted** [comment]
Well, Blosc is more geared towards compressing binary data, and that means knowing the number of bytes for the datatypes of the buffers to compress.  Unfortunately, the kernel does not have access to this information.
