### ISSUE TITLE
blosc_set_nthreads segfaults if blosc_init hasn't been called

### ISSUE THREAD

**Issue by aldanor** [Blosc/c-blosc#150]
Is it intentional behaviour or should it not try to call `blosc_destroy` if `blosc_init` hasn't been called yet? The segfault is in `blosc_release_threadpool`.

**Comment by FrancescAlted** [comment]
Yeah, `blosc_init()` allocates a thread pool, so it makes no sense to call `blosc_destroy()` (which deallocates the pool) before `blosc_init()`.  However, a segfault is not desirable, right.

**Comment by aldanor** [comment]
Should `blosc_set_nthreads` just call `blosc_init` if `!g_initlib`, perhaps?

**Comment by FrancescAlted** [comment]
I think the correct thing to do is to call `blosc_init()` first.  Regarding the segfault, some protection should be added to `blosc_destroy()` so that if `blosc_init()` has not been called, then no action should be done.

**Comment by dswanepoel** [comment]
Does `blosc_set_nthreads()` actually have to call `blosc_init()`? It seems that the thread pool is actually (re)allocated in `blosc_set_nthreads_()` when the number of threads change, and the number of threads doesn't affect anything done by `blosc_init()`. The `multithread.c` example still works if you remove `blosc_init()` and `blosc_destroy()` from `blosc_set_nthreads()`.

**Comment by FrancescAlted** [comment]
@dswanepoel I tried your suggestion, but `multithread.c` hangs forever.  blosc_destroy() is already out of the thread loop in the example, so not sure how this is working for you.

**Comment by FrancescAlted** [comment]
Anyway, the OP requirement was addressed in [C-Blosc 1.9.0](https://github.com/Blosc/c-blosc/commit/21ad195fff535638663afd74dc9ace618e9d6281), so closing this.
