### ISSUE TITLE
What are supported platforms?

### ISSUE THREAD

**Issue by hadley** [Blosc/c-blosc#151]
Sorry if I missed it, but I didn't see anything in the read me describing which platforms are supported.

**Comment by FrancescAlted** [comment]
The intended supported platforms are all that have a c89 compliant C compiler.  The tested ones are Intel, ARM and IBM Blue Gene Q embedded "A2" processor).

**Comment by FrancescAlted** [comment]
After reflection, I think this is actually a good point and added a new section about this in the README in commit 2c0d473.

**Comment by hadley** [comment]
Thanks!
