### ISSUE TITLE
hdf5 folder removed?

### ISSUE THREAD

**Issue by msarahan** [Blosc/c-blosc#155]
Is there a new way to have blosc as a filter for HDF5?  This seems to have been removed between 1.6.1 and 1.7.0.  I would like to use 1.7.0 for PyTables, but can't, now that this folder is gone.

**Comment by FrancescAlted** [comment]
The hdf5 wrapper lives in its own repo now: https://github.com/Blosc/hdf5-blosc

**Comment by msarahan** [comment]
Excellent, thank you for the pointer.
