### ISSUE TITLE
blosc_decompress_ctx bug fix for multithreaded case

### ISSUE THREAD

**Issue by chriswebers** [Blosc/c-blosc#158]
There have been several reports that blosc_decompress_ctx crashes with more than one thread. I think it is the following bug:

In blosc_decompress_ctx(), the initialisation of 
   context.threads_started = 0 
comes too late.
It needs to be moved before the call to blosc_run_decompression_with_context().
(Tested on OS X 10.11.3)

This may also be related to 
https://github.com/Blosc/c-blosc/issues/84
https://github.com/Blosc/c-blosc/issues/154
https://github.com/PyTables/PyTables/issues/412

**Comment by FrancescAlted** [comment]
Well spotted.  Fixed in c73691a.  Can others try to see if this alleviate things in referenced bugs (#84, #154, PyTables/PyTables#412 or even PR https://github.com/Blosc/bcolz/pull/285 )?  As bcolz is not using _ctx versions I don't think it will be very helpful, but it might help PyTables stability indeed.

**Comment by buybackoff** [comment]
I believe it already worked with the latest 1.7 commit before this one as I reported in #84. I have [updated](https://github.com/Spreads/Spreads/commit/5cbe4da155635260f908f67f423e7789ec96ab8c) and tested my project with this commit and it also works well.

**Comment by chriswebers** [comment]
It did work sometimes before, and especially in the first call(s) to blosc_decompress_ctx() because:
a) some compilers may have initialised the record field 'context.threads_started' to zero after allocating memory, or
b) the memory location for the local variable 'context' happened to have value zero.all the time.
So it worked 'by chance' but not 'by design' :-)

That made it hard to track. As all others before me I spent quite some time debugging the pthread part before I spotted this.

**Comment by FrancescAlted** [comment]
Yeah, so #84 should have been a different issue.  Thanks for reporting @buybackoff .

And @chriswebers, this should have been difficult to track indeed.  Oh the joy of threading and shared memory...  Maybe I should pay more attention to other paradigms like message passing between threads (à la 0mq).

**Comment by buybackoff** [comment]
I had an issue when blosc_decompress_ctx returned -1 for valid data on x86 server (on an x64 client I added assertion that decompressed payload equals original, the error was on a server with the same payload). blosc_cbuffer_sizes returned valid numbers as well. After upgrading to 1.7.1 the issue looks like disappeared. Could that be related to the bug from this issue by @chriswebers? It is strange that is was not a crash as originally reported.
