### ISSUE TITLE
Set up CMake / AppVeyor CI builds for VS2008

### ISSUE THREAD

**Issue by jack-pappas** [Blosc/c-blosc#162]
AppVeyor includes VS2008 (vc9) tools on their CI instances; since blosc is used by both Python 2.x and 3.x (in addition to other languages) and Python 2.x requires VS2008 on Windows, it'd be helpful to add a VS2008 build to the AppVeyor build matrix (in the ``appveyor.yml``) to help make sure any changes made to the library don't break compatibility with VS2008.

**Comment by FrancescAlted** [comment]
Agreed.  Added VS2008 (as well as VS2010 and VS2013) in 5020ca1.

**Comment by FrancescAlted** [comment]
FYI, I have added VS2010 because it is required by Python 3.3 and 3.4 (I think 3.5 starts using VS2015).
