### ISSUE TITLE
268 - test_compressor (Failed) for i386 build in OS X 10.11

### ISSUE THREAD

**Issue by selasley** [Blosc/c-blosc#169]
commit e06e3b13e built with Apple LLVM version 7.3.0 (clang-703.0.31) from Xcode 7.3.1 and make 3.5.1   The x86_64 version passes all tests. If the CMAKE_OSX_ARCHITECTURES flag is set to i386 in order to build a 32 bit version of libblosc,  ctest  -VV returns

99% tests passed, 1 tests failed out of 1616
Total Test time (real) =  97.68 sec
The following tests FAILED:
	268 - test_compressor (Failed)
Errors while running CTest

test 268
        Start 268: test_compressor
268: Test command: src/c-blosc/build/tests/test_compressor
268: Test timeout computed to be: 9.99988e+06
268: STARTING TESTS for src/c-blosc/build/tests/test_compressor.....F (ERROR: BLOSC_SHUFFLE=BITSHUFFLE does not work correctly)
268: 	Tests run: 6
268/1616 Test #268: test_compressor ..............................***Failed    0.08 sec

The 32 bit build of libblosc.1.9.0 fails the same test
The 32 bit build of libblosc.1.8.1 passes all tests but I don't know if it tests BLOSC_SHUFFLE=BITSHUFFLE

**Comment by FrancescAlted** [comment]
Yes, the [test that is failing](https://github.com/Blosc/c-blosc/blob/master/tests/test_compressor.c#L162) was introduced for 1.9.0.  It would be nice if you could print the values of `cbytes` and `cbytes2` in your platform and send it back (I would like to check if bitshuffle is just disabled or it is creating havoc).

Although quite tested already, bitshuffle was introduced relatively few time ago, and reports like this help a lot in polishing the rough edges.

**Comment by selasley** [comment]
for the i386 build
```
test_bitshuffle: cbytes =  226600, 0x37528, 00000000000000110111010100101000
test_bitshuffle: cbytes2 = 288316, 0x4663C, 00000000000001000110011000111100

```
for the x86_64 build
```
test_bitshuffle: cbytes =  226600, 0x37528, 00000000000000110111010100101000
test_bitshuffle: cbytes2 = 206298, 0x325DA, 00000000000000110010010111011010

```

**Comment by FrancescAlted** [comment]
Thanks.  As the original size of the buffer in the test is 8 MB, bitshuffle + codec is compressing indeed (although just 27x in i386 mode instead of 39x for the amd64 mode).  Hmmm, I don't see why bitfilter should behave differently on i386 vs amd64, but this is not necessarily a bug.  I suppose I need to update the test and do not assume that bitfilter always allows better ratios on this dataset.

Pinging @kiyo-masui so as to see if he has a hint on what's going on here.

**Comment by FrancescAlted** [comment]
For what is worth, [Windows tests pass in both 32-bit and 64-bit modes in AppVeyor](https://ci.appveyor.com/project/FrancescAlted/c-blosc/branch/master) so probably this issue is not universal.  A good idea would be to setup a virtual machine with a Linux 32-bit and test there too.

**Comment by kiyo-masui** [comment]
I'm not super familiar with the Blosc test suit so forgive me if I'm interpreting this wrong. Bitshuffle (+ which backend?) is compressing better on some architectures than others. What instruction sets do the two architectures use?

This does concern me: I worry that a dataset compressed under one architecture will be improperly compressed under another. Is there an easy way to perform that test?

**Comment by selasley** [comment]
A 32 bit build in a virtual 64 bit Linux Mint 7.3 system with gcc-4.8 fails with cbytes=226600, cbytes2=288316.  A 64 bit build passes all tests, cbytes=226600, cbytes2=206298.

A 32 bit build in a virtual 32 bit Linux Mint 7.3 system with gcc-4.8 fails with cbytes=226600, cbytes2=288316.  I could not get the tests to work with a 64 bit build on the 32 bit system.

**Comment by FrancescAlted** [comment]
@kiyo-masui the codec backend used in the test is blosclz, but I am pretty sure that the effect would show in other codecs too.  And I agree that the main issue here is that a dataset compressed in an arch would not decompress well in another (and not the different compression ratios, athough it would be nice to know what's going one there).  Fortunately, now that @selasley checked that Linux 32-bit already exposes the same behaviour it is easier to test for such a possible incompatibility.

**Comment by FrancescAlted** [comment]
I have been doing some tests, and the problem seems to happen only for LZ4 (yeah, this was the one used in the test, so I was wrong above).  These are results on a Linux (Ubuntu 16.04) 32-bit box, and using the python-blosc wrapper for convenience:

```
In [1]: import numpy as np

In [2]: import blosc

In [3]: a = np.arange(1000, dtype=np.int64)

In [4]: len(blosc.pack_array(a, shuffle=blosc.SHUFFLE, cname="lz4"))
Out[4]: 579

In [5]: len(blosc.pack_array(a, shuffle=blosc.BITSHUFFLE, cname="lz4"))
Out[5]: 702

In [6]: len(blosc.pack_array(a, shuffle=blosc.SHUFFLE, cname="blosclz"))
Out[6]: 580

In [7]: len(blosc.pack_array(a, shuffle=blosc.BITSHUFFLE, cname="blosclz"))
Out[7]: 641

In [8]: len(blosc.pack_array(a, shuffle=blosc.SHUFFLE, cname="zlib"))
Out[8]: 595

In [9]: len(blosc.pack_array(a, shuffle=blosc.BITSHUFFLE, cname="zlib"))
Out[9]: 461
```

and here with Linux (Ubuntu 16.04) 64-bit:

```
In [1]: import numpy as np

In [2]: import blosc

In [3]: a = np.arange(1000, dtype=np.int64)

In [4]: len(blosc.pack_array(a, shuffle=blosc.SHUFFLE, cname="lz4"))
Out[4]: 579

In [5]: len(blosc.pack_array(a, shuffle=blosc.BITSHUFFLE, cname="lz4"))
Out[5]: 632

In [6]: len(blosc.pack_array(a, shuffle=blosc.SHUFFLE, cname="blosclz"))
Out[6]: 580

In [7]: len(blosc.pack_array(a, shuffle=blosc.BITSHUFFLE, cname="blosclz"))
Out[7]: 641

In [8]: len(blosc.pack_array(a, shuffle=blosc.SHUFFLE, cname="zlib"))
Out[8]: 595

In [9]: len(blosc.pack_array(a, shuffle=blosc.BITSHUFFLE, cname="zlib"))
Out[9]: 461
```

so, all the figures are the same *except* for LZ4 and BITSHUFFLE which differ from 32-bit (702 bytes) to 64-bit (632 bytes).

The effect can be much higher for larger datasets.  For Linux 32-bit:

```
In [10]: a = np.arange(1000*1000, dtype=np.int64)

In [11]: len(blosc.pack_array(a, shuffle=blosc.SHUFFLE, cname="lz4"))
Out[11]: 53082

In [12]: len(blosc.pack_array(a, shuffle=blosc.BITSHUFFLE, cname="lz4"))
Out[12]: 203549

In [13]: len(blosc.pack_array(a, shuffle=blosc.SHUFFLE, cname="blosclz"))
Out[13]: 70442

In [14]: len(blosc.pack_array(a, shuffle=blosc.BITSHUFFLE, cname="blosclz"))
Out[14]: 67165
```

whereas for Linux 64-bit:

```
In [10]: a = np.arange(1000*1000, dtype=np.int64)

In [11]: len(blosc.pack_array(a, shuffle=blosc.SHUFFLE, cname="lz4"))
Out[11]: 53082

In [12]: len(blosc.pack_array(a, shuffle=blosc.BITSHUFFLE, cname="lz4"))
Out[12]: 110016

In [13]: len(blosc.pack_array(a, shuffle=blosc.SHUFFLE, cname="blosclz"))
Out[13]: 70442

In [14]: len(blosc.pack_array(a, shuffle=blosc.BITSHUFFLE, cname="blosclz"))
Out[14]: 67165
```

so something quite bizarre happens with LZ4 in 32-bit platforms (possibly not on Windows, only on UNIX) and this particular dataset passed through the BITSHUFFLE filter. 

Also, I tried to compress this dataset with LZ4 and BITSHUFFLE on a 32-bit machine and decompress in a 64-bit machine and everything works fine, so it is just LZ4 compressing quite less on 32-bit platforms, but apparently this does not affect the integrity of the compressed dataset.  On 32-bit:

```
In [15]: import bcolz

In [17]: ca = bcolz.carray(a, cparams=bcolz.cparams(cname="lz4", shuffle=bcolz.BITSHUFFLE), rootdir="a.bcolz")

In [18]: ca
Out[18]: 
carray((1000000,), int64)
  nbytes: 7.63 MB; cbytes: 491.95 KB; ratio: 15.88
  cparams := cparams(clevel=5, shuffle=2, cname='lz4')
  rootdir := 'a.bcolz'
  mode    := 'a'
[     0      1      2 ..., 999997 999998 999999]
```

After copying this to the 64-bit box:

```
In [21]: ca = bcolz.open("a.bcolz")

In [22]: ca
Out[22]: 
carray((1000000,), int64)
  nbytes: 7.63 MB; cbytes: 491.95 KB; ratio: 15.88
  cparams := cparams(clevel=5, shuffle=2, cname='blosclz')
  rootdir := 'a.bcolz'
  mode    := 'a'
[     0      1      2 ..., 999997 999998 999999]
```

so fortunately everything seems fine here.

Pinging @Cyan4973 just in case he has some hints here.  Yann, I tried to isolate the dataset passed through the BITSHUFFLE filter, but Blosc splits the datasets internally and that takes time, but if interested, tell me and I will put more time on this.

**Comment by Cyan4973** [comment]
Indeed, I confirm that LZ4 32-bits and 64-bits versions can compress files differently,
though both compress into a valid format that can be decoded by any version.

Reason is : the 64-bits variant use 64-bits arithmetic, for better speed, leading to different match finds.
It's also in general a little bit better than the 32-bits version, although you could probably find some counter-examples.

**Comment by FrancescAlted** [comment]
Thanks @Cyan4973 for confirming.  I suppose that the case that I found (2x more compression for 8 MB buffers in 64-bit archs) is a bit of an outlier, but it is a relief to know that everything is ok here.

**Comment by Cyan4973** [comment]
2x is really way more than I would expect, considering the differences between 32 and 64 bits versions.
Let's see if it's an outlier, or if it repeats again on a different sample.

**Comment by kiyo-masui** [comment]
I'm surprised by the difference actually. For one, we are talking about a very compressible dataset of incrementing integers. We're talking about compression ratios of 40 vs 80. Secondly, Bitshuffle does trade match proximity for run length, so this might be expected.

I think the differences will be much smaller for a less contrived dataset.
