### ISSUE TITLE
Any plans for JNI bindings?

### ISSUE THREAD

**Issue by lomereiter** [Blosc/c-blosc#170]
Hi there,

Thanks for the superb library!

I noticed there are no Java bindings/implementation listed on the front page, and it seems to hurt adoption somewhat, judging from e.g. this discussion where Snappy has been chosen instead, apparently just because of that: https://github.com/arq5x/gemini/issues/700

**Comment by FrancescAlted** [comment]
No plans here. Maybe a separate JNI bindings project would make sense though.

Sent from my phone

El 7 juny 2016, a les 16:35, Artem Tarasov <notifications@github.com> va escriure:
