### ISSUE TITLE
Incorrect library id for dynamic blosc library on OSX

### ISSUE THREAD

**Issue by matthew-brett** [Blosc/c-blosc#175]
A standard build on OSX results in a dynamic library that has an unqualified library `id` (the first entry in the table below):

```
$ otool -L /Users/mb312/tmp/lib/libblosc.dylib
/Users/mb312/tmp/lib/libblosc.dylib:
	libblosc.1.dylib (compatibility version 1.0.0, current version 1.10.2)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
```

This should be the full path to the binary, so that other libraries linking against it know where it is on the system, as in:

```
	/Users/mb312/tmp/libblosc.1.dylib (compatibility version 1.0.0, current version 1.10.2)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
        ...
```

See: http://matthew-brett.github.io/docosx/mac_runtime_link.html#install-names-and-static-absolute-or-relative-paths

I noticed this when trying to run `delocate` on a built pytables wheel:

https://travis-ci.org/MacPython/pytables-wheels/jobs/148589260#L5825

**Comment by FrancescAlted** [comment]
This should be fixed now.  Could you please see if that works for you?  Thanks.

**Comment by FrancescAlted** [comment]
Copying [my comment](https://github.com/Blosc/c-blosc/commit/980779d0fc25880547eb024cfe2e7ef22789e630#commitcomment-18464526) here for better following this discussion:

No, with this macro I don't think programs need any help to link with the blosc library. For example, the python-blosc package compiled with $ python setup.py build --blosc=/usr/local where the blosc library is in /usr/local (PREFIX):

$ otool -L /usr/local/lib/libblosc.dylib 
/usr/local/lib/libblosc.dylib:
    @rpath/libblosc.1.dylib (compatibility version 1.0.0, current version 1.10.3)
    libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
    /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
works well for me without no need to set RPATH to PREFIX.

At any rate, I am not very familiar with this stuff. You may want to experiment with cmake options in https://cmake.org/Wiki/CMake_RPATH_handling and tell me which one you prefer for further discussion.
