### ISSUE TITLE
DOES IT ONLY SUPPORT INTEL CPU? Could it support powerpc?

### ISSUE THREAD

**Issue by toneliu** [Blosc/c-blosc#192]
I wanna use this lib in powerpc arch. But till now, it only support avx2 and sse2.

**Comment by FrancescAlted** [comment]
PowerPC should be supported, although certainly not using its SIMD extensions.  If it does not compile for you please submit the errors that you are getting.  Thanks.

**Comment by FrancescAlted** [comment]
Closing this.  Feel free to re-open it in case it is necessary.
