### ISSUE TITLE
Feedstock update to post release actions?

### ISSUE THREAD

**Issue by FrancescElies** [Blosc/c-blosc#196]
Hi

I just created a PR on conda-forge https://github.com/conda-forge/blosc-feedstock/pull/13
I was wondering if you wanted to include this in the post-release actions so that every time that we have a release we also update the feedstock on conda.

This question applies to the rest of the blosc ecosystem too, python-blosc, blosckpack ...
This question is related to https://github.com/Blosc/python-blosc/issues/118

What do you think?

Best

**Comment by FrancescAlted** [comment]
Hmm, we recently tried to build binaries for C-Blosc, but we finally gave up.  One of the reasons why I am not a big fan of binary releases is that, for compatibility reasons, they usually are generated with old-ish compilers and you have to renounce to use recent hardware acceleration machinery (i.e. AVX2).  While this is usually not a big problem for other libraries, I consider this like a *big* drawback for a library like C-Blosc that is meant for *extreme* speed.

In addition, we are in era where you can install good free compilers (even on Windows) in an easy way, while CMake allows for a relatively easy build experience too.  For these reasons, my current position is that we should not be responsible of generating binaries for C-Blosc and that it is much better that users take responsibility for compiling on their own.  This is not to say that I would like to prevent 3rd parties to build binaries if they want to, but they should not be taken as a reference (most specially in terms of speed).

Hope this makes sense to you.

**Comment by FrancescElies** [comment]
Thanks for the explanation 👌 , closing this one!
