### ISSUE TITLE
Disable Snappy support by default

### ISSUE THREAD

**Issue by FrancescAlted** [Blosc/c-blosc#201]
Snappy is a C++ codec that creates unnecessary complexity in building tools (see https://github.com/Blosc/python-blosc/issues/127#issuecomment-324706140), so provided that there are better codecs giving better speed and compression (e.g. LZ4), I propose it to be disabled by default.

**Comment by nmoinvaz** [comment]
This looks like it is done, do you want to go a step further and remove building snappy from sources but allow testing against external snappy (similar to c-blosc2)?

**Comment by FrancescAlted** [comment]
Yes, that would be cool.
