### ISSUE TITLE
Snappy multi-thread support with typesize = 1 byte

### ISSUE THREAD

**Issue by tbiedert** [Blosc/c-blosc#202]
Hello,
the Snappy compressor does not work correctly when number of threads > 1 and `typesize` = 1 byte. Data can be  decompressed correctly, but compression ratio is close to memcpy.

Same behavior independent of `clevel` and `doshuffle`.

It does work correctly though for `typesize` = 2 or 4 bytes for instance.   Maybe a general question here: Is `typesize` = 1 byte a bad idea?

I'm using c-blosc-1.2.1. Same for both in-source and system Snappy (Ubuntu 17.04 package).

I have created a simple test program:

```
#include <vector>
#include <iostream>
#include <iomanip>

#include <blosc.h>

int main(int argc, char* argv[])
{
    std::vector<uint8_t> input(10000000, 0); // 10 MB of zeroes
    std::vector<uint8_t> output(input.size() + BLOSC_MAX_OVERHEAD);

    std::vector<const char*> compressors = { "snappy", "blosclz", "lz4", "lz4hc", "zlib", "zstd" };

    blosc_init();

    for (int i = 1; i <= 8; i *= 2)
    {
        std::cout << std::endl << "--- Threads: " << i << " ---" << std::endl;

        blosc_set_nthreads(i);

        for (const char* compressor : compressors)
        {
            blosc_set_compressor(compressor);

            int compressedBytes = blosc_compress(9, 1, sizeof(uint8_t), input.size(), input.data(), output.data(), output.size());

            float ratio = compressedBytes * 100.0f / input.size();
            std::cout << std::string(compressor) << ": " << std::fixed << std::setprecision(1) << ratio << "%" << std::endl;
        }
    }

    return 0;
}
```

Output is:
```
--- Threads: 1 ---
snappy: 4.7%
blosclz: 0.4%
lz4: 0.4%
lz4hc: 0.4%
zlib: 0.1%
zstd: 0.0%

--- Threads: 2 ---
snappy: 99.6%
blosclz: 0.4%
lz4: 0.4%
lz4hc: 0.4%
zlib: 0.1%
zstd: 0.0%

--- Threads: 4 ---
snappy: 99.6%
blosclz: 0.4%
lz4: 0.4%
lz4hc: 0.4%
zlib: 0.1%
zstd: 0.0%

--- Threads: 8 ---
snappy: 99.6%
blosclz: 0.4%
lz4: 0.4%
lz4hc: 0.4%
zlib: 0.1%
zstd: 0.0%
```

(Maybe this is already known or even documented somewhere, but I couldn't find anything related.)

Thanks!

**Comment by FrancescAlted** [comment]
That's weird indeed.  To be frank, I don't know why this is behaving like this: all the codecs are treated similarly in the compression pipeline of Blosc ([see here on the actual snappy wrappers inside Blosc](https://github.com/Blosc/c-blosc/blob/master/blosc/blosc.c#L442)).  OTOH, Snappy never gave specially good results inside Blosc, and besides, the fact that is C++ creates some integration headaches with other projects, so my intention is to make it a second-class citizen for Blosc2.  Is there any special reason why you are interested in Snappy?

**Comment by tbiedert** [comment]
Thanks for the feedback! I'm not interested in Snappy per se; I just noticed the weird behavior in above comparison. Feel free to get rid of it.. :-)

**Comment by FrancescAlted** [comment]
See also #201.
