### ISSUE TITLE
Build Multithreaded?

### ISSUE THREAD

**Issue by ahendry2688** [Blosc/c-blosc#209]
Is there support to build c-blosc with multiple cores in cmake using the typical `cmake -jN ..`, where `N` is the number of threads?

**Comment by FrancescAlted** [comment]
I usually use: 

```
cmake ..
make -j4
```

Is that what you are asking?

**Comment by ahendry2688** [comment]
Wait...you use `cmake` and then GNU `make`?
(but yes, I'm asking about the `-j` flag)

**Comment by FrancescAlted** [comment]
Yes, that's quite usual when using Unix machines.  I suppose that you are using Windows, so you must check how cmake for Windows work.
