### ISSUE TITLE
blosc_compress_ctx should be able to set split mode

### ISSUE THREAD

**Issue by asomers** [Blosc/c-blosc#231]
The new split mode feature introduced in version 1.14.0 looks handy, but it can only be set globally.  It should also configurable as an argument to `blosc_compress_ctx`, so multithreaded applications can take advantage of it.
http://blosc.org/posts/new-forward-compat-policy/

**Comment by FrancescAlted** [comment]
Agreed, but adding a new parameter to `blosc_compress_ctx` would mean backwards incompatibility.  I don't think that setting the split mode globally via `blosc_set_splitmode()` is that bad.  Is it?

**Comment by asomers** [comment]
It's bad if, like I am, you're writing blosc language bindings that avoid any use of global variables at all.  Can you at least ensure that blosc2 won't require any globals?

**Comment by FrancescAlted** [comment]
Yes, that's exactly the idea.  For Blosc2 there will be contexts (called, see an example here: [schunk](https://github.com/Blosc/c-blosc2/blob/master/examples/delta_schunk_ex.c#L64)) for all the operations (except the ones that should keep compatibility with Blosc1, of course).  Closing.
