### ISSUE TITLE
blosc_compress_ctx missing bounds check

### ISSUE THREAD

**Issue by dadkins1** [Blosc/c-blosc#234]
Calling blosc_compress_ctx with the destsize parameter smaller than the size of a compression header results in memory modified beyond the limits of dest + destsize. I would expect to see a failure returned if destsize is smaller than BLOSC_MIN_HEADER_LENGTH (or perhaps BLOSC_MAX_OVERHEAD).

**Comment by FrancescAlted** [comment]
Good catch.  Thanks!

**Comment by esc** [comment]
This might have lead to breakage as outlined here:

#246 and #242
