### ISSUE TITLE
ubuntu Or CentOS_unknown type name  pth read_barrier_t

### ISSUE THREAD

**Issue by NickSong** [Blosc/c-blosc#235]
/usr/compress/c-blosc2/build/blosc/context.h:93:3: error: unknown type name  pth
read_barrier_t
   pthread_barrier_t barr_init;
/usr/compress/c-blosc2/build/blosc/blosc.c:101:24: error: PTHREAD_BARRIER_SERIA
L_THREAD undeclared (first use in this function)
   if (rc != 0 && rc != PTHREAD_BARRIER_SERIAL_THREAD) { \

**Comment by FrancescAlted** [comment]
Strange.  I routinely run Blosc tests in Ubuntu and never seen this before.  Can you add more info on which Ubuntu or CentOS are you seeing this error?  Also, how do you build Blosc there?

**Comment by FrancescAlted** [comment]
Do you specify ``..`` to cmake?  The next works for me (using Ubuntu 18.04 here):

```
$ pwd
/home/francesc/blosc/c-blosc2/build
$ cmake ..
$ cmake --build .
```

**Comment by NickSong** [comment]
First:  I download source code in /usr/compress/c-blosc2
Second: modify CMakeList.txt  ,add   'set(CMAKE_SYSTEM_NAME Linux)'. Then do things below
$ mkdir build
$ cd build
$ cmake ..
$ cmake --build .
Error happend.....
my system is Ubuntu 16.04.4

**Comment by NickSong** [comment]
maybe __USE_XOPEN2K not define

**Comment by FrancescAlted** [comment]
I think you are missing the pthread development package in your system.  My advice is that you locate the package with `apt search pthread` and install it.

**Comment by NickSong** [comment]
The result is  must not set CMAKE_SYSTEM_NAME Linux^_^
