### ISSUE TITLE
unrecognized command line option -msse2 and -mavx2

### ISSUE THREAD

**Issue by NickSong** [Blosc/c-blosc#236]
I cross compile this project use below enviroment.
$ uname -a
Linux SZX1000443543 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
$ cmake -version
cmake version 3.11.3
ADD three set in CMakeList.txt
set(CMAKE_FIND_ROOT_PATH /usr/compress/gcc-linaro-7.1.1-2017.08-x86_64_aarch64-linux-gnu)
SET(CMAKE_C_COMPILER /usr/compress/gcc-linaro-7.1.1-2017.08-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc)
SET(CMAKE_CXX_COMPILER /usr/compress/gcc-linaro-7.1.1-2017.08-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-g++)

**Comment by NickSong** [comment]
I modified CMakeList.txt， set COMPILER_SUPPORT_AVX2 and COMPILER_SUPPORT_SSE2 false, then it can work.

**Comment by FrancescAlted** [comment]
Ok.  I can see the use case.  Now, you can disable the generation of SSE2 and AVX2 instructions without modifying the CMakeList.txt at all, and using command line:

```
$ cmake -DDEACTIVATE_SSE2=ON -DDEACTIVATE_AVX2=ON ..
Configuring for Blosc version: 1.14.4.dev
<snip>
-- Building for system processor x86_64
<snip>
```

Without activating these variables:

```
$ cmake ..
Configuring for Blosc version: 1.14.4.dev
<snip>
-- Building for system processor x86_64
-- Adding run-time support for SSE2
-- Adding run-time support for AVX2
<snip>
```
