### ISSUE TITLE
Issue with bitshuffle effectiveness

### ISSUE THREAD

**Issue by tdenniston** [Blosc/c-blosc#240]
Hello,

I think there may be an issue with the effectiveness of Blosc's bitshuffle filter. When compressing with blosc-lz4 some synthetic data (consecutive int32 values) after a byte shuffle versus after a bitshuffle, the byte-shuffled data compresses quite a bit more, which is unexpected. Due to the nature of the data being compressed, I expected bitshuffle to perform better than it seems to.

I've attached an example program to illustrate. With byte shuffle:

```
$ ./shuffle
Using Blosc 1.14.4
Input size = 400000000, compressed size = 3604149
```

With bit shuffle:

```
$ ./shuffle bitshuffle
Using Blosc 1.14.4
Input size = 400000000, compressed size = 18630089
```

Anecdotally, I set up an experiment using the [standalone bitshuffle](https://github.com/kiyo-masui/bitshuffle) code and the standalone LZ4 library, and the same data compressed more effectively than using blosc-lz4 with bitshuffle. It still did not compress as well as the byte-shuffled version, but it was more like ~2x over the byte-shuffled version rather than the above ~5x.

The `shuffle` program:

```c++
#include <blosc.h>
#include <cstdint>
#include <iostream>
#include <string>

int main(int argc, char **argv) {
  int shuffle = BLOSC_SHUFFLE;
  if (argc > 1 && std::string(argv[1]) == "bitshuffle")
    shuffle = BLOSC_BITSHUFFLE;

  // Generate data
  const unsigned ncells = 100000000;
  const unsigned input_nbytes = ncells * sizeof(int32_t);
  auto input = new int32_t[ncells];
  for (unsigned i = 0; i < ncells; i++)
    input[i] = i;

  // Compress
  auto output_size = input_nbytes + BLOSC_MAX_OVERHEAD;
  auto output = new uint8_t[output_size];
  int clevel = 9;
  int rc = blosc_compress_ctx(clevel, shuffle, sizeof(int32_t), input_nbytes,
                              input, output, output_size, "lz4", 0, 1);

  std::cout << "Using Blosc " << blosc_get_version_string() << std::endl;
  std::cout << "Input size = " << input_nbytes << ", compressed size = " << rc
            << std::endl;

  delete[] output;
  delete[] input;

  return 0;
}
```

I built `shuffle` with `g++ -std=c++11 -g -O0 shuffle.cc -o shuffle -lblosc`. My system supports AVX2.

**Comment by FrancescAlted** [comment]
Hi.  Probably the issue here is that Blosc splits the buffer internally (for a number of reasons, but mainly for performance), so the compression ratio may suffer for this case.  So as to avoid the split, I'd suggest to add a call to [blosc_set_blocksize](https://github.com/Blosc/c-blosc/blob/master/blosc/blosc.h#L485) with a value equal to the data chunk to be compressed prior to compression.  Alternatively, you can use the [BLOSC_BLOCKSIZE](https://github.com/Blosc/c-blosc/blob/master/blosc/blosc.h#L197) environment variable so you won't need to recompile your program.

**Comment by tdenniston** [comment]
@FrancescAlted, thanks for the fast reply! I modified my invocation of blosc in the above test program to the following:

```c++
  blosc_set_blocksize(input_nbytes);
  int rc = blosc_compress_ctx(clevel, shuffle, sizeof(int32_t), input_nbytes,
                              input, output, output_size, "lz4", input_nbytes,
                              1);
```

My understanding is that now the data being compressed will be treated as a single block. With this modification, the bitshuffled compression ratio was unaffected (the compressed sizes with both byteshuffle and bitshuffle stays the same as reported in my first post).

**Comment by FrancescAlted** [comment]
Yes, that should have been enough.  That's wierd...

**Comment by cgmb** [comment]
I had the same experience compressing a big array of floats representing particle positions (x, y, z). I wasn't sure what parameters to use, so I tried cycling through all of them and checking which combinations gave me the best compression ratios. As far as I could tell, `BLOSC_SHUFFLE` always provided a superior compression ratio to `BLOSC_BITSHUFFLE`.

I'm using the Ubuntu 18.04 libblosc-dev package on a Haswell i7, and I was calling `blosc_compress_ctx` with just about every combination of arguments I could imagine. Block size was the only option I didn't test exhaustively, but I did try a wide variety of sizes (including the default and the whole buffer).

**Comment by FrancescAlted** [comment]
Ok, it is curious because the bitshuffle code in blosc sohould be the same than the [standalone bitshuffle](https://github.com/kiyo-masui/bitshuffle).  Maybe it is time for an update inside blosc and see if that ameliorates the issue.  Volunteers?

**Comment by cgmb** [comment]
I didn't look into this as carefully as tdenniston. I only compared the built-in shuffle and bitshuffle. I never tried it with the standalone version. My apologies if I caused any confusion.

I was just surprised it had a worse ratio. Though, looking at the bitshuffle paper now, I'm realizing that the shuffle operations works a little differently than I had thought.

I had expected that the column width was a variable chosen by heuristic, and thus bitshuffle would always be able to match shuffle by choosing a column width in bits equal to whatever shuffle chose in bytes (plus a little per-block bookkeeping overhead, as bit indexes would be slightly larger than byte indexes).

Skimming through the bitshuffle paper, it seems that bitshuffle always uses 1-bit columns. Presumably shuffle always uses 1-byte columns. In that case, it's entirely expected that shuffle could be noticeably better for some data. Opps.

**Comment by FrancescAlted** [comment]
Exactly, you cannot assume that bitshuffle always compress better than shuffle, only experimentation can tell so.  Another issue is that the standalone bitshuffle is giving better results than the version inside blosc (although it should not, and this is why I was asking whether some volunteer would like to dig more into this).

**Comment by FrancescAlted** [comment]
I have been finally able to track this down.  The issue was that bitshuffle was not applied to the leftovers of a chunk (i.e. the part of the chunk that is beyond the last complete block).  I have [fixed this just in c-blosc2](https://github.com/Blosc/c-blosc2/pull/100), but it is not planned to backport it to c-blosc1 due to forward-compatibility issues (see https://github.com/Blosc/c-blosc2/pull/100 for a rational on why).

Here are the results with the new c-blosc2 library:

```
$ LD_LIBRARY_PATH=/tmp/c-blosc2/build/blosc ./test_bitshuffle_cratio bitshuffle
Using Blosc 2.0.0-beta.5.dev
Input size = 400000000, compressed size = 9423464
``` 

whereas with c-blosc1:

```
$ LD_LIBRARY_PATH=../../c-blosc/build/blosc ./test_bitshuffle_cratio bitshuffle
Using Blosc 1.17.2.dev
Input size = 400000000, compressed size = 18630089
```
