### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by AndreasMartin72** [Blosc/c-blosc#243]
Hi. I compile blosc with a slightly older gcc on linux (redhat). There are then many errors on modifier "inline" since it isn't supported in C. So with some comments //-style.
If I comment out the "inline"s and correct // to /* */, compile succeeds.
Perhaps you can fix this in your repo...

Kindly regards,
Andreas

**Comment by FrancescAlted** [comment]
Yes, that's fine. Could you send a pull request for this?

El dl., 5 nov. 2018, 11.15, Andreas Martin <notifications@github.com> va
escriure:

**Comment by AndreasMartin72** [comment]
Done.

**Comment by FrancescAlted** [comment]
Fixed in PR #244

**Comment by FrancescAlted** [comment]
Thanks @AndreasMartin72
