### ISSUE TITLE
Prefixing symbol names

### ISSUE THREAD

**Issue by jbms** [Blosc/c-blosc#254]
Many internal functions are given generic names like "shuffle".  They are given hidden visibility, which avoids linking problems when dynamically linking, but that doesn't help when using static linking.  To resolve this, all internal functions could be prefixed with "blosc_internal_".  If the maintainers are open to that change, I can provide a pull request.

**Comment by jbms** [comment]
To clarify, this problem only applies to non-static functions.

**Comment by FrancescAlted** [comment]
You raised a very good point.  We don't usually make use of the static library, so yeah, we would appreciate improvements in this area.
