### ISSUE TITLE
blosc_decompress_ctx fails if dest is too long

### ISSUE THREAD

**Issue by cgohlke** [Blosc/c-blosc#261]
I just upgraded from c-blosc 1.15.1 to 1.16.1 and get two test errors in the [imagecodecs](https://pypi.org/project/imagecodecs/) Python package when passing a `dest` buffer to `blosc_decompress_ctx` which is deliberately too long. `blosc_decompress_ctx` now returns `-1`. It that intentionally or a bug?

**Comment by FrancescAlted** [comment]
The 1.16 release adds more safety to corrupted/untrusted during decompression. Can you offer a more accurate description of your test so as to see if the new code is unnecessarily cautious?

**Comment by cgohlke** [comment]
Basically the tests compress an input of a certain `size` (2 or 3069), then try to uncompress the result using `blosc_decompress_ctx` into an output buffer with a length of that same `size` plus `1021`.

**Comment by FrancescAlted** [comment]
Yep, I was able to reproduce this.  Fixed in commits e08631dbf7810ccca7491008d8a8818779d4a113 and a45499455722c8505cb092c9661236e24c83765a.

**Comment by cgohlke** [comment]
Thank you!
