### ISSUE TITLE
Symbols check is failing

### ISSUE THREAD

**Issue by FrancescAlted** [Blosc/c-blosc#265]
From the blosc mailing list:

> we are currently experiencing issues building the conda-forge feedstock
> for Blosc (c-blosc 1):
> 
> https://github.com/conda-forge/blosc-feedstock/pull/35
> 
> The failures are related to the following tests:
> 
> The following tests FAILED:
>         1605 - blosc_test_shared_symbols (Failed)
>         1606 - blosc_test_static_symbols (Failed)
> 
> And only happen on Linux using Circle-CI and Azure-Pipelines.
> 
> We would be very grateful if anyone with more in  depth experience with
> the c-blosc buildsystem could take a look.

@jbms any hint on this one?

**Comment by FrancescAlted** [comment]
Now the symbol checks are deactivated by default.  Use `cmake .. -DDEACTIVATE_SYMBOLS_CHECK=ON` to re-activate them if you are interested.

**Comment by jbms** [comment]
Unfortunately the symbols check is a bit brittle in that different platforms/build configurations can affect the symbol names, and also result in additional compiler-generated symbols.  For that reason, disabling the check in automated builds, especially ones that aren't easily reproduced or debugged, probably makes sense.  It could make sense to keep them enabled on travis and appveyor, but you may not want the additional nuisance.

It should be easy for me to fix this particular breakage, but it would require the output from the failing tests, which can be gotten by running ctest with CTEST_OUTPUT_ON_FAILURE=1 (as the conanbuild.py file does), or by running check_symbols.py manually on the built library.

**Comment by FrancescAlted** [comment]
I see. These errors stem from PRs like https://github.com/conda-forge/blosc-feedstock/pull/35. Maybe you can submit a PR there and check by yourself?

**Comment by esc** [comment]
So, the 1.16.3 release fixed the Linux builds via conda-forge, but now the windows builds are broken with a different error, though. The PR is still the same though:

https://github.com/conda-forge/blosc-feedstock/pull/35

**Comment by esc** [comment]
Seems like it was CI glitch, v1.6.3 arrived on the Anaconda cloud (conda-forge) channel last night. Please feel free to close this issue.
