### ISSUE TITLE
Support OpenPower vector instruction set.

### ISSUE THREAD

**Issue by kif** [Blosc/c-blosc#267]
The pre-filtering in *blosc* is virtually costless when implemented with SIMD instructions. I noticed strong performance (speed) degradation when using bitshuffle on IBM Power9. Is there an easy way to re-implement the bitshuffle using their vector instructions ? Could you provide us some help in doing this ?

Here are some figures for compressing images of int32:
```
Blosc        lz4         NO Compression rate: 2.880;	Compression speed: 10225.625 MB/s
Blosc        lz4     BYTE Compression rate: 4.273;	Compression speed: 10586.137 MB/s
Blosc        lz4        BIT Compression rate: 9.045;	Compression speed: 4879.911 MB/s
```

**Comment by FrancescAlted** [comment]
If your "BYTE compression" is what we call the "shuffle filter", then I am quite (and happily) surprised to see that its use does not affect performance on POWER9.

Regarding bitshuffle for POWER9, we don't have experience with that in our team, but you can have a look at how shuffle and bitshuffle for NEON in ARM have been implemented in Blosc2:

https://github.com/Blosc/c-blosc2/blob/master/blosc/shuffle-neon.c
https://github.com/Blosc/c-blosc2/blob/master/blosc/bitshuffle-neon.c

While the shuffle for NEON is totally operative, there are still some rough edges for bitshuffle for NEON.  However, you may still use this implementation so as to figure out how the support for filters for different architectures has been implemented in Blosc2 and do a similar thing for POWER9.  Good luck!

**Comment by kif** [comment]
Yes the "byte" is for byte-shuffle preprocessor and apparently the lack of SIMD does not impact the performances. Unfortunately, for the bit-shuffle it does hurt performances. Those tests were performed using python-blosc as the performances of c-blosc are much lower due to the absence of any optimization on POWER9

I just had a look at some doc from IBM and apparently since gcc-8 it is possible to have an automatic replacement of x86 intrinsics with their VMX and VSX instructions. I just tested on the SSE2 and AVX2 code: it work (compiles) for the first but not for the second. Maybe this is a path to explore.

**Comment by FrancescAlted** [comment]
Support for POWER9 SIMD is happening in Blosc2 (e.g. https://github.com/Blosc/c-blosc2/pull/89) and it is not expected to be backported in Blosc1.
