### ISSUE TITLE
Recommendations for ppc64le and aarch64

### ISSUE THREAD

**Issue by ax3l** [Blosc/c-blosc#268]
Hi,

what CMake flags do you recommend for building on ppc64le and aarch64?
Currently, building for these platforms gives the warnings:

- PPC64le CMake: #267
```
CMake Warning at CMakeLists.txt:253 (message):
  Unrecognized system processor ppc64le.  Cannot determine which hardware
  features (GNU 8.2.0) supports, so hardware-accelerated implementations will
  not be available.
```
- ARM64 CMake:
```
CMake Warning at CMakeLists.txt:253 (message):
  Unrecognized system processor aarch64.  Cannot determine which hardware
  features (GNU 7.3.0) supports, so hardware-accelerated implementations will
  not be available.
```

Afair, at least for PPC64le, AVX2 might be a thing. Should one just add the processor [in the list](https://github.com/Blosc/c-blosc/blob/v1.16.3/CMakeLists.txt#L206-L210)?
See: https://github.com/conda-forge/blosc-feedstock/pull/36

**Comment by FrancescAlted** [comment]
The support for ARM and PPC is happening in the [c-blosc2 project, the new generation](https://github.com/Blosc/c-blosc2).  Please check it out, in particular https://github.com/Blosc/c-blosc2/pull/59.

**Comment by ax3l** [comment]
Thanks for the info, that looks like a great effort! Looking forward to blosc2! :)
