### ISSUE TITLE
[question] how to build with C++ code/lib?

### ISSUE THREAD

**Issue by jamboo2017** [Blosc/c-blosc#269]
Hi,
I want to add a new filter (RLEv2 from Apache ORC). The filter is written in C++ (class).
I see there are 2 ways: 1) build c-blosc2 with g++ instead of gcc; 2) add a wrapper to the RLE C++ code and link to c-blosc2 with g++.
For 1), I tried to add project(blosc LANGUAGES CXX) to CMakeList.txt, but there are lots of error messages when linking (CMake can not determine linker language for target: xxx).

So my question is: is there a known good method to mix C++ code within c-blosc? How?
Thanks.

**Comment by FrancescAlted** [comment]
Hi @jamboo2017 .  When you say filters, you probably mean codec?  (I think Run Length Encoding is a compression codec). New codecs are welcome in [Blosc2](https://github.com/Blosc/c-blosc2) (Blosc1 header just have to little space for encoding maybe 1 more, whereas in [Blosc2 the codecs can be stored in the super-chunk too](https://github.com/Blosc/c-blosc2/blob/master/README_HEADER.rst)).

Having said that, we want to keep Blosc2 away from including C++ code.  If you could provide a RLEv2 based on C99 (or older), I'd happy to evaluate it and see if it fits well in Blosc2.

**Comment by bobjiang82** [comment]
Thanks @FrancescAlted for the quick response.
It may sound strange but I'm trying to add RLE as a filter like shuffle/bitshuffle/delta filters. The purpose is to make a comparison with bitshuffle on compress ratio and speeds ...
I only see JAVA and C++ RLEv2 code from https://github.com/apache/orc. I'll try to look for a C version.
