### ISSUE TITLE
Distribute a pkg-config file

### ISSUE THREAD

**Issue by nemequ** [Blosc/c-blosc#27]
A [pkg-config](http://www.freedesktop.org/wiki/Software/pkg-config/) file for the shared library would be appreciated.

**Comment by keszybz** [comment]
Added in https://github.com/Blosc/c-blosc/commit/499d52af31944d05593ab3abc21a4f8728fe5712. This can be closed now.

**Comment by FrancescAlted** [comment]
Right.
