### ISSUE TITLE
test_forksafe compile fails with icc

### ISSUE THREAD

**Issue by glennpj** [Blosc/c-blosc#271]
When using the Intel icc compiler to build c-blosc, there is a failure building test_forksafe.

```console
...
tests/test_forksafe.c
            (45): error: identifier "sec" is undefined
     448        for(float sec = 0; sec < 1; ) {
...
```
I suspect a header and/or macro issue but I am not exactly sure where sec is defined.

Thanks.

**Comment by FrancescAlted** [comment]
I have just tried, and it work well on my Linux box:

```
$ CC="icc" cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
<snip>
$ make -j4
<snip>
[100%] Linking CXX static library libblosc.a
[100%] Built target blosc_static
$ ctest
<snip>
100% tests passed, 0 tests failed out of 1651

Total Test time (real) =  80.71 sec
$ icc -v
icc version 19.0.4.243 (gcc version 7.4.0 compatibility)
```

Maybe a newer icc version should fix the problem?

**Comment by FrancescAlted** [comment]
At any rate, I have just declared `sec` out of the for loop in 7d8ef2e.  Closing, but feel free to reopen it if your icc continues to complain.
