### ISSUE TITLE
Integrating with OSS-Fuzz

### ISSUE THREAD

**Issue by Google-Autofuzz** [Blosc/c-blosc#274]
Greetings c-blosc developers and contributors,

We’re reaching out because your project is an important part of the open source ecosystem, and we’d like to invite you to integrate with our [fuzzing](https://www.owasp.org/index.php/Fuzzing) service, [OSS-Fuzz]( https://opensource.googleblog.com/2016/12/announcing-oss-fuzz-continuous-fuzzing.html ). OSS-Fuzz is a free fuzzing infrastructure you can use to identify security vulnerabilities and stability bugs in your project. OSS-Fuzz will:

- Continuously run at scale all the fuzzers you write.
- Alert you when it finds issues.
- Automatically close issues after they’ve been fixed by a commit.

Many widely used [open source projects]( https://github.com/google/oss-fuzz/tree/master/projects ) like OpenSSL, FFmpeg, LibreOffice, and ImageMagick are fuzzing via OSS-Fuzz, which helps them find and remediate [critical issues]( https://bugs.chromium.org/p/oss-fuzz/issues/list?can=1&q=status%3AFixed%2CVerified+Type%3ABug%2CBug-Security+-component%3AInfra+ ). 

Even though typical integrations can be done in < 100 LoC, we have a [reward program]( https://www.google.com/about/appsecurity/patch-rewards/ ) in place which aims to recognize folks who are not just contributing to open source, but are also working hard to make it more secure.

We want to stress that anyone who meets the eligibility criteria and integrates a project with OSS-Fuzz is eligible for a reward.

To help you getting started, we can attach our internal fuzzer for your project that you are welcome to use directly, or to use it as a starting point.

If you're not interested in integrating with OSS-Fuzz, it would be helpful for us to understand why—lack of interest, lack of time, or something else—so we can better support projects like yours in the future.

If we’ve missed your question in our [FAQ]( https://google.github.io/oss-fuzz/faq/ ), feel free to reply or reach out to us at oss-fuzz-outreach@googlegroups.com.

Thanks!

Tommy
OSS-Fuzz Team

---

```C

#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#include "third_party/blosc/blosc.h"

extern "C" int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {
  if (size < BLOSC_MIN_HEADER_LENGTH) return 0;

  size_t nbytes, cbytes, blocksize;
  blosc_cbuffer_sizes(data, &nbytes, &cbytes, &blocksize);
  if (cbytes != size) return 0;
  if (nbytes == 0) return 0;

  void *output = malloc(nbytes);
  blosc_decompress_ctx(data, output, nbytes, /*numinternalthreads=*/1);
  free(output);
  return 0;
}
```

**Comment by FrancescAlted** [comment]
Yes, it would be certainly interesting to try to integrate C-Blosc with OSS-Fuzz (as time allows).   Could you please proceed with attaching the fuzzer for us to use directly (or as a starting point, don't know well the difference yet)?  Also, we might be interested in applying to the reward program too (doing open source is certainly time consuming, so incentives are welcome!).

**Comment by Google-Autofuzz** [comment]
Oops, I forgot to add it in my first message, it's now edited and present, sorry :)

**Comment by Google-Autofuzz** [comment]
> Yes, it would be certainly interesting to try to integrate C-Blosc with OSS-Fuzz (as time allows). Could you please proceed with attaching the fuzzer for us to use directly (or as a starting point, don't know well the difference yet)? Also, we might be interested in applying to the reward program too (doing open source is certainly time consuming, so incentives are welcome!).

If lack of time is the issue, we can help out to start the integration of C-Blosc to OSS-Fuzz :)  Would you want us to start on it for this C-Blosc?

**Comment by FrancescAlted** [comment]
> If lack of time is the issue, we can help out to start the integration of C-Blosc to OSS-Fuzz :) Would you want us to start on it for this C-Blosc?

Yes, unfortunately we don't have that much time lately, so feel free to provide us with a good start on this one.  Thanks!

**Comment by Google-Autofuzz** [comment]
Do you have a google email address that we can use to send bugs if OSS-Fuzz finds them? @FrancescAlted

**Comment by FrancescAlted** [comment]
Ok.  I have just created `blosc.oss.fuzz@gmail.com` and forwarded to me initially.  In the future we can expand the forwarding list to more people in the team.

**Comment by FrancescAlted** [comment]
Closing as per #296
