### ISSUE TITLE
Version numbering in Conan package

### ISSUE THREAD

**Issue by stefan-gavranovic** [Blosc/c-blosc#275]
Is there a specific reason why you start the version number with preceding letter v? 

This causes problems when this package is being used alongside with cmake_find_package generator.  A lot of projects are using `find_package(<package> [version])` where `version` must be just a number sequence `major.minor.patch`. Preceding v brakes this check.

**Comment by FrancescAlted** [comment]
No, this should be an oversight on my side.  Would you mind contributing a PR with a fix?

**Comment by nmoinvaz** [comment]
This can be closed since Conan package deprecated.

**Comment by Croydon** [comment]
For people looking for a Conan package: It is also available via the Conan Center https://conan.io/center/c-blosc/1.18.1/ 😄
