### ISSUE TITLE
Disable C++ compiler detection

### ISSUE THREAD

**Issue by FrancescAlted** [Blosc/c-blosc#284]
C-Blosc should not need a C++ compiler by default (snappy is not compiled by default anymore), but cmake insist in finding one.  Here one can see how to avoid this detection: https://stackoverflow.com/questions/12023879/let-cmake-not-detect-c-compiler

**Comment by nmoinvaz** [comment]
I believe this issue can be closed now.

**Comment by FrancescAlted** [comment]
Yep.
