### ISSUE TITLE
Blosc should use CXX linker when shared and snappy static

### ISSUE THREAD

**Issue by SpaceIm** [Blosc/c-blosc#285]
I'm creating a conan recipe of Blosc for https://github.com/conan-io/conan-center-index

Except msvc, I had lot of undefined reference to libstdc++ symbols (due to Snappy), when linking Blosc into an executable.

Seems like Blosc doesn't use C++ linker if external Snappy (static) and shared Blosc.

I've solved this pb by patching blosc/CMakeLists.txt:
````patch
@@ -193,6 +135,9 @@ endif()
 
 if (BUILD_SHARED)
     target_link_libraries(blosc_shared ${LIBS})
+    if(NOT DEACTIVATE_SNAPPY)
+        set_target_properties(blosc_shared PROPERTIES LINKER_LANGUAGE CXX)
+    endif()
     target_include_directories(blosc_shared PUBLIC ${BLOSC_INCLUDE_DIRS})
 endif()
 
````

(you can also have a look here: https://github.com/SpaceIm/conan-c-blosc)

If both Snappy and Blosc are static, responsibility of using C++ linker lies to the consumer of Blosc...

**Comment by FrancescAlted** [comment]
Closing as per #295.
