### ISSUE TITLE
Fails to build on multiple architectures.

### ISSUE THREAD

**Issue by havardAasen** [Blosc/c-blosc#289]
I am having trouble building c-blosc on several architectures in Debian. It succeeds on amd64 , arm64, i386, mips64el and ppc64el.

This means that it fails to build on armel, armhf, mipsel and s390x

I'm am not sure if these architectures is supported, but they succeeded with the 1.17.1 release.
When I rebuild the 1.17.1 version now, it fails on the same architectures.

The latest change in Debian is cmake update from 3.15.4 → 3.16.3 and gcc 9.2.1 → 9.3.0
I am not certain if either is the root cause for the failure. The build log is attached.

[c-blosc_1.18.1+ds1-1_armel.build.txt](https://github.com/Blosc/c-blosc/files/4454438/c-blosc_1.18.1%2Bds1-1_armel.build.txt)

The failure starts with:
```
CMake Error at /usr/share/cmake-3.16/Modules/CMakeCompilerIdDetection.cmake:26 (list):
list sub-command REMOVE_ITEM requires two or more arguments.
Call Stack (most recent call first):
/usr/share/cmake-3.16/Modules/CMakeDetermineCompilerId.cmake:211 (compiler_id_detection)
/usr/share/cmake-3.16/Modules/CMakeDetermineCompilerId.cmake:230 (CMAKE_DETERMINE_COMPILER_ID_WRITE)
/usr/share/cmake-3.16/Modules/CMakeDetermineCompilerId.cmake:32 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
/usr/share/cmake-3.16/Modules/CMakeDetermineCXXCompiler.cmake:111 (CMAKE_DETERMINE_COMPILER_ID)
CMakeLists.txt:78 (project)
```
It fails to find the CXX compiler, it does find the C compiler.
`-- The CXX compiler identification is unknown`

The usual warning about unrecognized system processor
```
Building for system processor armv7l
CMake Warning at CMakeLists.txt:250 (message):
Unrecognized system processor armv7l.  Cannot determine which hardware
features ( ) supports, so hardware-accelerated implementations will not be
available.
```
Continues with
```
Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
Compiler: /usr/bin/cc
Build flags: -g;-O2;-fdebug-prefix-map=/<<PKGBUILDDIR>>=.;-fstack-protector-strong;-Wformat;-Werror=format-security;-Wdate-time;-D_FORTIFY_SOURCE=2
Id flags: -c

The output was:
1
CMakeCCompilerId.c:20:52: error: expected ‘,’ or ‘;’ before ‘COMPILER_ID’
  20 | char const* info_compiler = "INFO" ":" "compiler[" COMPILER_ID "]";
     |                                                    ^~~~~~~~~~~
 ```
Before it eventually fails.

**Comment by FrancescAlted** [comment]
It looks like an issue in the build chain for some platforms to me, but I am not an expert at that either :-/

**Comment by havardAasen** [comment]
Your correct. I wasn't running native hardware which caused the issue. Should have tested it further before raising an issue here.

Sorry for the inconvenience.
