### ISSUE TITLE
Buffer is uncompressible - for buffers with a short length

### ISSUE THREAD

**Issue by kubaroth** [Blosc/c-blosc#307]
Question: While running one of the examples, for input buffers with a short length I get: "Buffer is uncompressible.  Giving up". Is there any way to control the threshold at runtime with env variables?

**Comment by FrancescAlted** [comment]
Not currently.  Blosc is more geared towards large input buffers (say 4 KB or more), so not sure it makes sense to include support for smaller ones.  Which is the range of lengths that you are trying to use?  And, can you provide an scenario where these can be useful?

**Comment by kubaroth** [comment]
Thanks for clarification. There's no really good use case I can provide, I was just getting familiarized with the library and experimented with short inputs. The lack of compression confused me in the beginning. Perhaps a comment about the intended support can be added to the API (or the simple.c example) to make it clear.

**Comment by kubaroth** [comment]
Closing as the answer addressed my question.

**Comment by FrancescAlted** [comment]
For the record, this has been discussed here too. https://github.com/Blosc/c-blosc/issues/337#issuecomment-1182201412.
