### ISSUE TITLE
Update conda package of latest release 1.21.1?

### ISSUE THREAD

**Issue by steindev** [Blosc/c-blosc#330]
Hey,

an application I use uses c-blosc to write compressed output.
Now I wanted to read that output in a Jupyter notebook and realize, that the output of the application is not properly read into Jupyter.

I assume this is due to the application using blosc-1.21.1 to write the data, while the latest package available on conda-forge, being the version used to read the data in the jupyter notebook, is blosc-1.21.0.

Would you mind providing a conda package of the latest blosc release?

**Comment by mkitti** [comment]
For future reference, the conda-forge package for blosc is maintained by third party maintainers here:
https://github.com/conda-forge/blosc-feedstock/blob/main/recipe/meta.yaml

**Comment by mkitti** [comment]
As of right now, https://anaconda.org/conda-forge/blosc appears to use 1.21.1

**Comment by steindev** [comment]
> For future reference, the conda-forge package for blosc is maintained by third party maintainers here: https://github.com/conda-forge/blosc-feedstock/blob/main/recipe/meta.yaml

Ohh third party. I see. Thanks for your reply!
