### ISSUE TITLE
Switching from `master` to `main`

### ISSUE THREAD

**Issue by jakirkham** [Blosc/c-blosc#336]
Would like to suggest `c-blosc` rename its `master` branch to `main`.

There has been a concerted effort in the open source community broadly to rename `master` to `main` given the connotations associated with the former term.

GitHub itself has been trying to [make this transition smooth]( https://github.com/github/renaming ). There are also various blogposts and StackOverflow questions that can now be referenced on the topic.

Links redirect automatically after renaming. `HEAD` will be updated to point `main` when renaming the branch (note `HEAD` can be used in links).

GitHub forks and local repos would need to be updated, but messages would appear on both to make the change clear. Submodules use hashes so shouldn't be affected.

Sometimes docs and CI scripts need updates for the name change.

Not sure what other impacts there would be for c-blosc specifically (or other Blosc repos), but hopefully that gives a sense of what would be involved.

**Comment by FrancescAlted** [comment]
Sure.  Done.
