### ISSUE TITLE
Uncompressable data set?

### ISSUE THREAD

**Issue by DennisHeimbigner** [Blosc/c-blosc#337]
I was given the simple data set of float values.
The data was the sequence 1..80.
When I apply c-blosc using any of the LZ sub-compressors
and with shuffle off, I get an error that the dataset is uncompressable.
Is this known behavior of LZ, and is there a simple characterization
of uncompressable datasets?

**Comment by kalvdans** [comment]
Duplicate of https://github.com/Blosc/c-blosc/issues/307 ?

**Comment by esc** [comment]
>  and is there a simple characterization of uncompressable data

The Shannon entropy provides a good theoretical framework for charcaterising data that can not be compressed:

https://en.wikipedia.org/wiki/Entropy_(information_theory)

A more handwavy argument is that random data -- e.g. white noise -- or samples produced by a pseudo-random-number-generator, depending on the distribution that was samples from may not be very compressible at all.

**Comment by esc** [comment]
> > and is there a simple characterization of uncompressable data
> 
> The Shannon entropy provides a good theoretical framework for charcaterising data that can not be compressed:
> 
> https://en.wikipedia.org/wiki/Entropy_(information_theory)
> 
> A more handwavy argument is that random data -- e.g. white noise -- or samples produced by a pseudo-random-number-generator, depending on the distribution that was samples from may not be very compressible at all. Compression alogrithms look for patterns or repeated values in data, if there are no patterns and no repeated values they don't stand a good chance (w/o additional tricks, like shuffle).

IIRC from my time with blosc, is that the library will detect such patterns and simply copy the input to the output verbatim and adding the blosc-header as overhead, which leads to a contract about the maximum length needed for the blosc output buffer.

**Comment by DennisHeimbigner** [comment]
Thank you.

**Comment by FrancescAlted** [comment]
> IIRC from my time with blosc, is that the library will detect such patterns and simply copy the input to the output verbatim and adding the blosc-header as overhead, which leads to a contract about the maximum length needed for the blosc output buffer.

For the record, that's exactly what is happening here.  If the user do not provide space enough to host uncompressible data, then the [blosc_compress](https://c-blosc2.readthedocs.io/en/latest/reference/blosc1.html#c.blosc_compress) will fail.  But as is specified in the docs, passing a buffer with a `destsize=src_nbytes + BLOSC_MAX_OVERHEAD` size, it is guaranteed that the compression will 'succeed'.

**Comment by FrancescAlted** [comment]
As a side note, a naive way to 'characterize' uncompressible data is to use `destsize=src_nbytes` in `blosc_compress()`, and if it returns a negative value, that means that the data is uncompressible (for the compression parameters used, at least).
