### ISSUE TITLE
Upgrade ZSTD to 1.5.5 due to potential corruption 

### ISSUE THREAD

**Issue by mkitti** [Blosc/c-blosc#364]
See https://github.com/facebook/zstd/releases/tag/v1.5.5

**Comment by mkitti** [comment]
Resolved in https://github.com/Blosc/c-blosc/commit/7ddc78d8a5c65430f2abadb9affe40ddf897cd98

Release is pending

**Comment by FrancescAlted** [comment]
Thanks for the reminder.  Let's see if we have some free cycles for doing the release during next week.

**Comment by FrancescAlted** [comment]
C-Blosc 1.21.4 is out.  Closing.

**Comment by mkitti** [comment]
Thank you.
