### ISSUE TITLE
MinGW blosc_decompress_ctx decompression exception with -O3

### ISSUE THREAD

**Issue by buybackoff** [Blosc/c-blosc#84]
I have compiled the library with MinGW and am playing with different combinations of settings for `blosc_compress_ctx` and `blosc_decompress_ctx`. I call them from C# via PInvoke.

Everything works fine on a single call, but on repeated calls decompression fails. I narrowed the problem down to `numinternalthreads` in `blosc_decompress_ctx`: *when it is above 1*, repeated calls fail. I haven't noticed a pattern of failure yet, but input data and order of tests change the point of failure. Compression works OK with multiple threads.

Exceptions are `System.AccessViolationException` and [System.Runtime.InteropServices.SEHException: External component has thrown an exception.](http://msdn.microsoft.com/en-us/library/system.runtime.interopservices.sehexception%28v=vs.80%29.aspx) and have nothing to do with C#.

I could have compiled the library incorrectly, but compression and single-threaded decompression do work. Benchmark single also works well for all compressors...
...
And (after another hour) funny enough, everything works with -O1, -O2 optimization options and fails only with -O3 option (regardless of -g option). This -O3 option was set inside Makefile.mingw in `bench` folder, so I used it by default and was going to try to debug the code and switched to plain `-g2`.

Here is my C# code of decompress, nothing special (same as in Snappy.NET):
```
unsafe int INativeLibraryFacade.blosc_decompress_ctx(byte[] src, byte[] dest) {
            if (src == null) throw new ArgumentNullException("src");

            var destSize = new UIntPtr((uint)dest.Length);
            var numThreads = new IntPtr(4); //new IntPtr(System.Environment.ProcessorCount);
            checked { 
                fixed (byte* srcPtr = &src[0])
                fixed (byte* detPtr = &dest[0]) {
                    var decompSize = Native.blosc_decompress_ctx(
                        srcPtr, detPtr, destSize, numThreads);
                    if (decompSize <= 0) throw new ApplicationException("Invalid compression input");                   
                    return decompSize;
                } }
        }

... part of Native ...
[DllImport(LibraryName, CallingConvention = CallingConvention.Cdecl)]
        private static unsafe extern int blosc_decompress_ctx(byte* src, byte* dest,
                                    UIntPtr destsize, IntPtr numinternalthreads);
```

My test iterates over 1K arrays of doubles, decimals and longs with different settings (clevel = 9):
```
[Test]
        public void CouldCompressAndDecompress() {
            for (int round = 0; round < 100; round++) {
            // library and shuffle
            Compress(CompressionMethod.blosclz, true);
            Compress(CompressionMethod.blosclz, false);

            Compress(CompressionMethod.lz4, true);
            Compress(CompressionMethod.lz4, false);

            Compress(CompressionMethod.zlib, true);
            Compress(CompressionMethod.zlib, false);
            }
        }
```

**Comment by buybackoff** [comment]
Probably related to #82

**Comment by buybackoff** [comment]
After some further reading this is obviously related to #74, my MinGW gcc version is 4.9.2

**Comment by FrancescAlted** [comment]
That's strange.  At least on Linux, the only compressor that was affected was LZ4, but perhaps MinGW is uncovering other side effects by GCC 4.9 series :(.  What's the version of the c-blosc library that you are testing?  1.5.2 was known to work with GCC 4.9.1.

**Comment by buybackoff** [comment]
@FrancescAlted I am using master head as of yesterday

**Comment by buybackoff** [comment]
Just recompiled 1.5.2 - same thing, with O3 and number of threads above 1 `blosc_decompress_ctx` throws AccessViolationException

**Comment by buybackoff** [comment]
I was incorrect, all modes -O0..-O3 throw an exception with multiple decompression threads, -O3 throws AccessViolation, -O0 throws SEHException. I need to review the source and my interop code (if they match) and cross-compile on Linux for Windows with MinGW to be somewhat sure it is not my code.

What about x86? Is the code supposed to work without additional flags or anything when compiled with MinGW (i.e. was it tested by someone)? If yes then my build is likely broken, if no - then there is probably some issue with Windows/MinGW.

Single threaded is quite fast - faster than any other alternative I had before I have found this fascinating library! My main concern is stability though.

**Comment by FrancescAlted** [comment]
Can you try with some pre 1.5 version?

Enviat des del meu iPhone

El 15/01/2015, a les 19:47, Victor Baybekov <notifications@github.com> va escriure:

**Comment by buybackoff** [comment]
same with the first commit where the _ctx functions were introduced. https://github.com/Blosc/c-blosc/commit/ff6ca8efccd4baa1c08c6316e30c8483aadaa6b9

I haven't tried older functions which require init(). will come back after double check if my build is broken or not. The simplest way is to write the same test in pure C and debug.

**Comment by buybackoff** [comment]
When I set [this line](https://github.com/Blosc/c-blosc/blob/master/tests/test_basics.c#L180) to two threads the `test_basics.exe` crashes, with 1 thread it is OK. My experience with C and tooling is not enough yet to debug it.

**Comment by FrancescAlted** [comment]
Good to know, thanks.  Yeah, I strongly suspect that we introduced some multithreading glitch during the big revamp for 1.5 series.

**Comment by esc** [comment]
Without digging into it too much but judiging from the recent issues we have been seeing with bcolz, that is my gut feeling also.

**Comment by jack-pappas** [comment]
@buybackoff Can you check whether this issue is fixed by #87?

**Comment by buybackoff** [comment]
@jack-pappas  together with the [latest](https://github.com/Blosc/c-blosc/commit/109a2bcee301740595d59b0fe5834334017bceec) commit it doesn't help. Same crash after a couple of thousands iteration of compress/decompress calls via P/Invoke to _ctx versions on 2+ threads.

**Comment by jack-pappas** [comment]
Ah, that's unfortunate. The change in #87 seems to fix the hanging issue in the benchmark tool I reported in #82.

Btw, in the C# P/Invoke signature you provided above for ``blosc_decompress_ctx`` -- I think the type of the ``numinternalthreads`` parameter should be an ``int`` or ``uint``, not ``IntPtr``.

**Comment by buybackoff** [comment]
Thanks, fixed that. As long as I do not box integers and use a pointer to boxed int, but use just `new IntPtr(2)` could that matter?

BTW, I have realized that Blosc blocksize `blocksize = L1 * 4;` with clevel 9 `blocksize *= 2` is 16-32 times larger than my typical data (8-16Kb), since I cut large data sets into chunks myself before calling Blosc. So the issue became irrelevant from practical point of view as I do not need 2+ threads. But the error persists when data is larger than a single block.

**Comment by buybackoff** [comment]
With MinGW, x86 version crashed even with single thread. I recompiled the library with CMake+VS12, now x86 works fine with one thread, but the crash with 2+ threads remains with the same behavior.

**Comment by buybackoff** [comment]
Version 1.7 (compiled with CMake + VS2015RC) works great without exceptions, both x86 and x64

**Comment by FrancescAlted** [comment]
Cool.  Thanks for the feedback!
